import Navigation from "@/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ArtCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#F3F5F8] overflow-x-hidden w-full`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
